services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    ports:
      - 3000:3000
    env_file:
      - ./apps/reservations/.env

    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/auth/.env

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/payments/.env

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: npm run start:dev notifications

    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/notifications/.env

  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
