services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    ports:
      - 3000:3000
    env_file:
      - ./apps/reservations/.env

    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/auth/.env

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    ports:
      - 3002:3002
    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/payments/.env

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
